# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = VideoAnnotation
QT += quick multimedia
DESTDIR = ../x64/Debug
CONFIG += debug c++14
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./FileHelper.h
SOURCES += ./main.cpp \
           ./FileHelper.cpp
RESOURCES += qml.qrc
